#!/bin/sh 

#
# Program: download_package 
#
# Original Author: lnh
#
# Purpose:
#
#	Download files from a remote server to our local download directory.
#       Taking advantage of the structure already in place, it makes sense
#       we implement one script that can handle the download of any external package.
#       Each package will have its configuration file with the following global variables:
#       1) REMOTE_SITE  - package host
#       2) REMOTE_SITE_URL  - package site url (ftp://$REMOTE_SITE, or htp://$REMOTE_SITE)
#       3) REMOTE_DIR   - path to package on host
#       4) REMOTE_FILES - list of packages
#
# Usage : ./download_package package.config
# 
# Assumption: 
# 1) DATADOWNLOADS path  is set in Configuration file
# 2) MIRRORLOG directory is set in Configuration file
#
# What it does:
# 1) source the Configuration file 
# 2) source the Package specific Configuration file to access global environment variables
# 3) setup path to files locally and remotely
# 4) if local_directory path does not exist create it
# 5) Create a mirror_lock for this package
# 6) foreach file on the list, downloads a local copy
# 7) Write a log report
# 8) Remove the mirror_lock
# 9) exit
#
# Date: 2/25/2016
#
WGET=`which wget`

if [ $# -lt 1 ]
then
   echo "-----------------------------------------------"
   echo ""
   echo "Usage: ./download_package annotation_config_file"
   echo ""
   echo "------------------------------------------------"
   exit 1
fi
cd `dirname $0`
WORKING_DIR=`pwd`
THIS_CONFIG_FILE=$1
SCRIPT_NAME=`basename $0`
SERVER_NAME=`hostname -a`
REFSEQ_BASE="/data/downloads//refseq/release"
#echo "REFSEQ_BASE $REFSEQ_BASE"
#
# Check if package config file exists
#
if [ ! -f $THIS_CONFIG_FILE ]
then
  echo "The Configuration file $THIS_CONFIG_FILE is missing from $WORKING_DIR"
  exit 1
fi
#
#
# Check if the main config file exists
#
MAIN_CONFIG=$WORKING_DIR/Configuration

if [ ! -r $MAIN_CONFIG ]
then
  echo "The main Configuration file is missing from $WORKING_DIR"
  echo "Run the Install script "
  exit 1
fi
# source the main config file
. ${MAIN_CONFIG}

#source the config file specific to these annotations
. $THIS_CONFIG_FILE
#
# Set path of files on local server
#
if [ "$LOCAL_DIR" = "" ]
then
   LOCAL_DIR=$REMOTE_SITE$REMOTE_DIR
fi
LOCAL_DOWNLOAD_BASE=${DATADOWNLOADS}/$LOCAL_DIR

if [ $loca_dir_is_absolute  ]
then
    LOCAL_DOWNLOAD_BASE=$LOCAL_DIR
fi
LOCK_DIR=$LOCAL_DOWNLOAD_BASE
#
#setup the log
LOG_FILE="${MIRRORLOG}/$THIS_CONFIG_FILE.log"
rm -rf $LOG_FILE
touch $LOG_FILE
date | tee -a $LOG_FILE
#
#LOG current setting 
#
echo "------------------------------" | tee -a $LOG_FILE
echo "***** Remote site setting *****" | tee -a $LOG_FILE
echo "------------------------------" | tee -a $LOG_FILE
echo "Remote site: $REMOTE_SITE" | tee -a $LOG_FILE
echo "Remote directory: $REMOTE_DIR" | tee -a $LOG_FILE
echo "Files to download: $REMOTE_FILES" | tee -a $LOG_FILE
echo "------------------------------" | tee -a $LOG_FILE
echo "***** Local setting *****" | tee -a $LOG_FILE
echo "------------------------------" | tee -a $LOG_FILE
echo "Working directory is:$WORKING_DIR" | tee -a $LOG_FILE
echo "Running $SCRIPT_NAME on Server :$SERVER_NAME" | tee -a $LOG_FILE
echo "config file used: $THIS_CONFIG_FILE" | tee -a $LOG_FILE
echo "download directory: $LOCAL_DOWNLOAD_BASE" | tee -a $LOG_FILE
echo "locks directory: $LOCK_DIR" | tee -a $LOG_FILE
echo "mirror logs directory: $MIRRORLOG" | tee -a $LOG_FILE
echo "log: $LOG_FILE" | tee -a $LOG_FILE
echo "------------------------------" | tee -a $LOG_FILE

#
# Set path of files on local server
# Make parent directories as needed
if [ ! -d $LOCAL_DOWNLOAD_BASE ]
then
   echo "Creating new directory $LOCAL_DOWNLOAD_BASE"
   mkdir -p $LOCAL_DOWNLOAD_BASE
else
   if [ $LOCAL_DOWNLOAD_BASE = $REFSEQ_BASE ]
   then
       echo "Removing directory $LOCAL_DOWNLOAD_BASE and its contents"
       rm -rf $LOCAL_DOWNLOAD_BASE
       echo "Creating new directory $LOCAL_DOWNLOAD_BASE"
       mkdir -p $LOCAL_DOWNLOAD_BASE
   fi
fi

# attempt to set write lock
echo "Working directory is:$SERVER_NAME:`pwd`"

mirror_lock wlock mirror_wget ${LOCK_DIR} 2>&1 | tee -a  ${LOG_FILE}
if [ $? -ne 0 ] 
then
  echo "Run status= Failed - could not set mirror_lock.$REMOTE_SITE" | tee -a  ${LOG_FILE}
  echo "See logs at ${LOG_FILE}" | tee -a  ${LOG_FILE}
  echo "Stop Time: `date`" | tee -a  ${LOG_FILE}
  exit 1
fi
# cd to LOCAL_DOWNLOAD_BASE and run wget command 
##cd ${LOCAL_DOWNLOAD_BASE}
# delete local files as needed
##if [ "$do_deletes" = true ]
##then
##   echo "Current files: "
##   echo `ls -lh `
##   rm -f *
##fi
if [ $is_xml_query ]
then
   ##don't do the loop if this is a xml query string
   target_file="$REMOTE_SITE_URL$REMOTE_DIR/${REMOTE_FILES}"
   echo "---- $WGET $WGET_OPTIONS $target_file" | tee -a  ${LOG_FILE}
   cd ${LOCAL_DOWNLOAD_BASE}
   $WGET -a ${LOG_FILE} $WGET_OPTIONS "$target_file"
else
(
set -f
for remote_file in ${REMOTE_FILES}
do
   echo "$remote_file"
   target_file="$REMOTE_SITE_URL$REMOTE_DIR/$remote_file"
   echo "$WGET $WGET_OPTIONS $target_file" | tee -a  ${LOG_FILE}
   ## get the directory part from the remote_file name
   target_local_dir=`dirname $remote_file`
   echo "Creating new directory $target_local_dir"
   #
   # Make parent directories as needed
   if [ "$target_local_dir" != "" ]
   then
      if [ ! -d ${LOCAL_DOWNLOAD_BASE}/$target_local_dir ]
      then
          echo "Creating new directory ${LOCAL_DOWNLOAD_BASE}/$target_local_dir"
          mkdir -p ${LOCAL_DOWNLOAD_BASE}/$target_local_dir
      fi
   fi
   #cd to LOCAL_DOWNLOAD_BASE and run wget command 
   cd ${LOCAL_DOWNLOAD_BASE}/$target_local_dir 
   # delete local files as needed
   if [ "$do_deletes" = true ]
   then
       rm -f $remote_file
   fi
   $WGET -a ${LOG_FILE} $WGET_OPTIONS "$target_file" 
done
)
fi
#
#Un lock mirrors
#
cd $WORKING_DIR
echo "Running 'mirror_lock unlock mirror_wget' command from `pwd`"
mirror_lock unlock mirror_wget ${LOCK_DIR}  2>&1 | tee -a  ${LOG_FILE}
echo "$REMOTE_SITE annotations downloaded" | tee -a  ${LOG_FILE}
echo "Program complete"| tee -a  ${LOG_FILE}
echo "================================="| tee -a  ${LOG_FILE}
exit 0
